### ISSUE TITLE
Error: spawn EACCES

### ISSUE THREAD

**Issue by RiderSx** [edubkendo/atom-racer#27]
/usr/share/atom/resources/app.asar/src/buffered-process.js:260

Error: spawn EACCES
  at exports._errnoException (util.js:734:11)
  at ChildProcess.spawn (child_process.js:1145:11)
  at Object.exports.spawn (child_process.js:977:9)
  at BufferedProcess.module.exports.BufferedProcess.spawn (/usr/share/atom/resources/app.asar/src/buffered-process.js:188:44)
  at new BufferedProcess (/usr/share/atom/resources/app.asar/src/buffered-process.js:52:14)
  at /home/thers/.atom/packages/racer/lib/racer-client.coffee:41:23
  at /usr/share/atom/resources/app.asar/node_modules/temp/lib/temp.js:252:7
  at FSReqWrap.oncomplete (fs.js:77:15)

Config:
```
  racer:
    racerBinPath: "/home/thers/.local/share/racer/target/release"
    rustSrcPath: "/usr/local/src/rust/src"
```

**Comment by alkama** [comment]
Hello,

It doesn't say much but looks like a misconfiguration.
Look at the homepage and double check your configuration and that you setup things correctly.

Or post your config here.

Regards.

**Comment by RiderSx** [comment]
Sorry, it's all okay, was a bit confused about config, thought racer bin path is path to dir where bin sits :)

**Comment by alkama** [comment]
Glad it works now :)
Have a great day !
