### ISSUE TITLE
Uncaught Error: spawn ELOOP

### ISSUE THREAD

**Issue by umurgdk** [edubkendo/atom-racer#28]
[Enter steps to reproduce below:]

1. Open cargo based folder
2. Try to type something like "std".

**Atom Version**: 0.207.0
**System**: Mac OS X 10.10.3
**Thrown From**: [racer](https://github.com/edubkendo/atom-racer) package, v0.11.0

### Stack Trace

Uncaught Error: spawn ELOOP

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:260

Error: spawn ELOOP
  at exports._errnoException (util.js:734:11)
  at ChildProcess.spawn (child_process.js:1145:11)
  at Object.exports.spawn (child_process.js:977:9)
  at BufferedProcess.module.exports.BufferedProcess.spawn (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:188:44)
  at new BufferedProcess (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:52:14)
  at /Users/umurgedik/.atom/packages/racer/lib/racer-client.coffee:41:23
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/temp/lib/temp.js:252:7
  at FSReqWrap.oncomplete (fs.js:77:15)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ],
    "disabledPackages": [
      "emmet",
      "autocomplete-haxe"
    ]
  },
  "racer": {
    "rustSrcPath": "/Users/umurgedik/Applications/rust/src"
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-alignment, v0.12.1
atom-typescript, v4.5.7
autocomplete-paths, v1.0.2
build, v0.36.1
docblockr, v0.7.2
file-icons, v1.5.7
haxe, v0.6.1
language-haxe, v0.3.0
language-rust, v0.4.3
linter, v0.12.6
linter-rust, v0.1.0
racer, v0.11.0

# Dev
No dev packages
```

**Comment by alkama** [comment]
Set your racer binary path (complete).
The one in the box is an example, not a default one, you HAVE to set yours up.
Look at the readme and other closed issues.

**Comment by umurgdk** [comment]
Ah i think lint-rust causing the problem not yours. After set paths for cargo and rustc for lint-rust it started to work. Maybe users can be warned about this on readme.
